# Generated by Django 4.2.3 on 2023-08-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0018_delete_actionelement_delete_actionelementtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MSG', 'Message'), ('TXT', 'Text Input'), ('ACT', 'Action Call')], default='MSG', max_length=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('guide', models.TextField(blank=True, null=True)),
                ('audio', models.BooleanField(default=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.action')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action_element.actionelementtype')),
            ],
        ),
    ]
