# Generated by Django 4.2.3 on 2023-08-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_element', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionelement',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
