# Generated by Django 4.2.3 on 2023-08-11 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action_element', '0002_actionelement_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCall',
            fields=[
                ('actionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='action_element.actionelement')),
                ('button_label', models.CharField(default='Submit', max_length=256)),
            ],
            bases=('action_element.actionelement',),
        ),
    ]
