# Generated by Django 4.2.3 on 2023-08-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_element', '0003_agentcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionelementtype',
            name='name',
            field=models.CharField(choices=[('MSG', 'Message'), ('TXT', 'Text Input'), ('ACA', 'Agent Call')], default='MSG', max_length=3),
        ),
    ]
