# Generated by Django 4.2.3 on 2023-08-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_element', '0004_alter_actionelementtype_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentCall',
            new_name='ActionElementAgentCall',
        ),
    ]
