# Generated by Django 4.2.3 on 2023-08-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_element', '0005_rename_agentcall_actionelementagentcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionelementagentcall',
            name='mimesis_class',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
