# Generated by Django 4.2.3 on 2023-08-19 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action_element', '0006_actionelementagentcall_mimesis_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionElementMessage',
            fields=[
                ('actionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='action_element.actionelement')),
                ('message', models.TextField(blank=True, null=True)),
            ],
            bases=('action_element.actionelement',),
        ),
        migrations.CreateModel(
            name='ActionElementTextInput',
            fields=[
                ('actionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='action_element.actionelement')),
                ('message', models.TextField(blank=True, null=True)),
            ],
            bases=('action_element.actionelement',),
        ),
    ]
