# Generated by Django 4.2.3 on 2023-08-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_element', '0007_actionelementmessage_actionelementtextinput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionelement',
            name='audio',
        ),
    ]
