# Generated by Django 4.2.3 on 2023-08-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_element', '0008_remove_actionelement_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionelementtextinput',
            name='audio',
            field=models.BooleanField(default=True),
        ),
    ]
