# Generated by Django 4.2.3 on 2023-08-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_element', '0009_actionelementtextinput_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionelementagentcall',
            old_name='mimesis_class',
            new_name='mimesis_action',
        ),
    ]
