# Generated by Django 4.2.3 on 2023-08-21 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0010_instruction_preview'),
        ('action_element', '0011_actionelement_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionelement',
            name='instruction',
        ),
        migrations.AddField(
            model_name='actionelement',
            name='instruction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instruction.instructiontype'),
            preserve_default=False,
        ),
    ]
