# Generated by Django 4.2.3 on 2023-08-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_element', '0013_remove_actionelement_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionelementagentcall',
            name='document_input',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
