# Generated by Django 4.2.3 on 2023-08-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_element', '0014_actionelementagentcall_document_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionelementagentcall',
            name='working_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
