# Generated by Django 4.2.3 on 2023-09-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_element', '0015_actionelementagentcall_working_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionElement',
        ),
        migrations.DeleteModel(
            name='ActionElementAgentCall',
        ),
        migrations.DeleteModel(
            name='ActionElementMessage',
        ),
        migrations.DeleteModel(
            name='ActionElementTextInput',
        ),
        migrations.DeleteModel(
            name='ActionElementType',
        ),
    ]
