# Generated by Django 4.2.3 on 2023-07-22 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_traitdb_personalitydb_agentdb_personality'),
        ('projects', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agentdb'),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
