# Generated by Django 4.2.3 on 2023-07-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_message_agent_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
