# Generated by Django 4.2.3 on 2023-07-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.document'),
        ),
    ]
