# Generated by Django 4.2.3 on 2023-08-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0019_action_mimesis_class'),
        ('projects', '0024_remove_message_instruction_delete_instruction'),
        ('instruction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instruction',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actions.action'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instruction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
