# Generated by Django 4.2.3 on 2023-08-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0002_instruction_name_alter_instruction_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='prompt',
        ),
    ]
