# Generated by Django 4.2.3 on 2023-08-21 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0004_instructiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='name',
        ),
        migrations.AddField(
            model_name='instruction',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruction.instructiontype')
        ),
    ]
