# Generated by Django 4.2.3 on 2023-08-21 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0005_remove_instruction_action_remove_instruction_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instruction.instructiontype'),
            preserve_default=False,
        ),
    ]
