# Generated by Django 4.2.3 on 2023-08-21 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0006_alter_instruction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruction.instruction')),
            ],
        ),
        migrations.CreateModel(
            name='MessageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('html', models.TextField(blank=True, default='', null=True)),
                ('selectable', models.BooleanField(default=True)),
                ('selected', models.BooleanField(default=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruction.message')),
            ],
        ),
    ]
