# Generated by Django 4.2.3 on 2023-08-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0008_alter_message_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
