# Generated by Django 4.2.3 on 2023-08-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0009_instruction_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
