# Generated by Django 4.2.3 on 2023-08-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0010_instruction_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructiontype',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
