# Generated by Django 4.2.3 on 2023-08-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0012_instruction_show_as_possible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='show_as_possible',
            field=models.BooleanField(default=True),
        ),
    ]
