# Generated by Django 4.2.3 on 2023-09-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0014_instructionelement_instructionelementtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='preview',
            new_name='template',
        ),
    ]
