# Generated by Django 4.1.11 on 2023-09-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0015_rename_preview_instruction_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
