# Generated by Django 4.1.11 on 2023-09-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0016_instruction_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='step',
        ),
        migrations.AddField(
            model_name='instructiontype',
            name='step',
            field=models.IntegerField(choices=[(0, 'Write'), (1, 'Revise'), (2, 'Modify')], default=0),
        ),
    ]
