# Generated by Django 4.1.11 on 2023-09-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0017_remove_instruction_step_instructiontype_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
