# Generated by Django 4.1.11 on 2023-09-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0019_alter_instructionelementtype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionelementrevision',
            name='mimesis_action',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
