# Generated by Django 4.1.11 on 2023-09-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0020_instructionelementrevision_mimesis_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mimesis_action',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
