# Generated by Django 4.1.11 on 2023-09-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0021_message_mimesis_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='called',
            field=models.BooleanField(default=False),
        ),
    ]
