# Generated by Django 4.1.11 on 2023-09-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0024_instructionelementdocumentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionelementdocumentlink',
            name='label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
