# Generated by Django 4.1.11 on 2023-10-03 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('instruction', '0027_instructionelementagentcall_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
