# Generated by Django 4.1.11 on 2023-10-06 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0029_remove_instruction_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionElementRevise',
            fields=[
                ('instructionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='instruction.instructionelement')),
                ('button_label', models.CharField(default='Submit', max_length=256)),
                ('by_section', models.BooleanField(default=True)),
            ],
            bases=('instruction.instructionelement',),
        ),
        migrations.AlterField(
            model_name='instructionelementtype',
            name='name',
            field=models.CharField(choices=[('MSG', 'Message'), ('TXT', 'Text Input'), ('ACA', 'Agent Call'), ('RVS', 'Revise'), ('REV', 'Revision'), ('DOC', 'Document')], default='MSG', max_length=3),
        ),
    ]
