# Generated by Django 4.1.11 on 2023-10-09 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0030_instructionelementrevise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionelementrevision',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='message',
            name='called',
        ),
        migrations.RemoveField(
            model_name='message',
            name='mimesis_action',
        ),
        migrations.AddField(
            model_name='instructionelementrevision',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instruction.message'),
        ),
        migrations.AddField(
            model_name='instructionelementrevision',
            name='was_revised',
            field=models.BooleanField(default=False),
        ),
    ]
