# Generated by Django 4.1.11 on 2023-10-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0031_remove_instructionelementrevision_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructiontype',
            name='style',
            field=models.CharField(choices=[(0, 'Normal'), (1, 'Seamless')], default='Normal', max_length=64),
        ),
    ]
