# Generated by Django 4.1.11 on 2023-10-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0032_instructiontype_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructiontype',
            name='style',
            field=models.CharField(choices=[('normal', 'normal'), ('seamless', 'seamless')], default='normal', max_length=64),
        ),
    ]
