# Generated by Django 4.1.11 on 2023-10-12 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0033_alter_instructiontype_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionElementChoices',
            fields=[
                ('instructionelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='instruction.instructionelement')),
                ('choices', models.JSONField(blank=True, null=True)),
            ],
            bases=('instruction.instructionelement',),
        ),
        migrations.AlterField(
            model_name='instructionelementtype',
            name='name',
            field=models.CharField(choices=[('MSG', 'Message'), ('CHO', 'Choices'), ('TXT', 'Text Input'), ('ACA', 'Agent Call'), ('RVS', 'Revise'), ('REV', 'Revision'), ('DOC', 'Document')], default='MSG', max_length=3),
        ),
    ]
