# Generated by Django 4.1.11 on 2023-10-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_remove_document_is_format_document_format'),
        ('instruction', '0034_instructionelementchoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionelementchoices',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.format'),
        ),
    ]
