# Generated by Django 4.1.11 on 2023-10-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0034_instructionelementchoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionelementchoices',
            name='style',
            field=models.CharField(blank=True, choices=[('radio', 'Radio'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('chips', 'Chips')], max_length=256, null=True),
        ),
    ]
