# Generated by Django 4.1.11 on 2023-11-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0038_remove_instructionelementrevision_document_element_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructiontype',
            name='style',
            field=models.CharField(choices=[('normal', 'normal'), ('seamless', 'seamless'), ('flow', 'flow')], default='normal', max_length=64),
        ),
    ]
