# Generated by Django 4.1.11 on 2023-12-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0041_instructionelement_flow_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionelement',
            name='flow_visible',
            field=models.BooleanField(default=False),
        ),
    ]
