# Generated by Django 4.1.11 on 2023-12-09 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0002_prompt_created_at_prompt_created_by_and_more'),
        ('instruction', '0043_remove_instructionelement_flow_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionelementtextinput',
            name='feedback_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prompt.prompt'),
        ),
    ]
