# Generated by Django 4.1.11 on 2023-12-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0044_instructionelementtextinput_feedback_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionelement',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
