# Generated by Django 4.1.11 on 2023-12-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0045_instructionelement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionelementtextinput',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruction.instruction')),
                ('instruction_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruction.instructionelement')),
            ],
        ),
    ]
