# Generated by Django 4.1.11 on 2023-12-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0045_instructionelement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionelementtextinput',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
