name = "Write Job Profile"
description = "Write job profile"
definition = ""
memory = "I wrote a job profile"

[reply]
name = "job_profile"
type = "document"
revise = true

[prompt]
text = """Actúa como un encargado de recursos humanos de una empresa que debe construir el perfil de cargo de un empleado dentro de una compañía. 

Para ello, debes considerar los siguientes aspectos:

* Este perfil de cargo es para uso interno dentro del área de recursos humanos, y no es un aviso publicitario. Por ello es necesario que el perfil de cargo solicitado sea redactado en tercera persona.

* Para esta tarea, es necesario que no existan sesgos discriminatorios en la redacción del perfil del cargo.

* También es necesario que el perfil de cargo que escribas sea formal y detallado. 

* El perfil del cargo debe contar exclusivamente con las siguientes categorías:

# Título del puesto

# Resumen del puesto

# Objetivos y metas

# Responsabilidades y tareas

# Requisitos obligatorios

# Reporte jerárquico

# Evaluación del desempeño

# Ubicación

# Horario de trabajo

# Tipo de contrato

# Salario o rango salarial

# Beneficios

# Desarrollo profesional

# Cultura organizacional

# Fecha de inicio prevista

# Duración del contrato

# Requisitos legales y regulatorios

# Otros requisitos específicos.

Para realizar la descripción de cargo, considera la siguiente transcripción de audio de las necesidades que tiene la empresa. Esta transcripción describe una necesidad de la empresa. Tu objetivo es determinar qué rol podría solucionar estos problemas, y completar la descripción antes descrita.

{{job_role}}

A fin de que este perfil de cargo sea acorde al funcionamiento de la empresa, se te proveerá de un documento delimitado por ///. Este documento entrega información relevante sobre el rubro y los objetivos de la empresa y debe ser considerado a la hora de construir el perfil de cargo. Necesito que uses la descripción de la empresa para escribir la descripción del cargo. Usa la descripción de la empresa para inferir información.

Debes escribir [Completar] en caso de que en el texto delimitado por /// no exista información específica o literal para la redacción de las categorías de: Reporte jerárquico; Evaluación del desempeño; Ubicación, Horario de trabajo; Tipo de contrato; Salario o rango salarial; Beneficios; Fecha de inicio prevista; Duración del contrato; Requisitos legales y regulatorios; Otros requisitos específicos.

/// Información de la empresa

{{ documento_descriptivo }}

Falabella

Somos un ecosistema físico y digital líder en América Latina, con una propuesta de valor omnicanal de soluciones simples e intuitivas. La fortaleza de nuestros activos y capacidades nos da una ventaja clave para transformarnos constantemente, y ofrecer a nuestros clientes un journey unificado, sin intermediarios, en los siete países en que estamos presentes: Chile, Perú, Colombia, Brasil, México, Uruguay y Argentina.

Construido sobre plataformas sólidas y escalables—marketplace, payments, banking, omnichannel retail, loyalty y home delivery— el ecosistema opera tiendas por departamento, de mejoramiento del hogar, supermercados, e-commerce, sucursales bancarias, una billetera digital y centros comerciales regionales, bajo reconocidas marcas como Mallplaza, Falabella, Sodimac, Tottus, falabella.com y Banco Falabella. Además, contamos con oficinas de compra en China e India, y centros digitales en India, Chile, México y Argentina.

Simplificar y disfrutar más la vida es el propósito con el que trabajamos para quienes nos eligen todos los días. Esta visión común está en el centro de nuestras conversaciones y guía nuestros proyectos de transformación cultural y digital.

Para esto, estamos impulsando una profunda transformación cultural y una nueva manera de trabajar mirando a los próximos años, potenciando capacidades que ya son parte de nuestra propuesta de valor e incorporando otras nuevas. En este contexto, entendemos la necesidad de convertirnos en una organización más ágil y flexible, manteniendo nuestra tradición de tener al cliente y a nuestros colaboradores siempre al centro de toda nuestra gestión. Esta constante transformación cultural que impulsamos está basada en vivir y promover nuestros valores y principios corporativos, los cuales son claves para el desarrollo de la estrategia de Ecosistema y constituyen el motor de nuestras acciones en el día a día.
Respeto y Oportunidades: Falabella se compromete a respetar los derechos humanos y ha adherido al Pacto Global de las Naciones Unidas, enfocándose en derechos humanos, relaciones laborales, medio ambiente y anticorrupción.
Salario Falabella: La empresa asegura salarios competitivos y acordes con los costos de vida, utilizando metodologías como IPE y TRS de Mercer, además de estudios sobre el costo de vida en cada país donde opera.
Inclusión y Diversidad: Políticas activas de diversidad e inclusión, incluyendo enfoques en equidad de género, diversidad sexual y discapacidad. Iniciativas como Mujeres Conectadas y la Comunidad LGBT+ y Aliad@s son ejemplos de esto.
Educación y Desarrollo de Habilidades: Programas como la Escuela Digital para reconversión laboral y el Programa Haciendo Escuela, que apoya la educación de niños en situación vulnerable.
Salud y Seguridad Ocupacional: Compromiso con la salud física y mental de los colaboradores, siguiendo estándares internacionales como ISO 18.001 y estableciendo programas de prevención de riesgos.
Aprendizaje Continuo: Iniciativas para el desarrollo de habilidades y competencias, como el Programa Líderes de Ecosistema y programas de reconversión digital.
Publicidad Responsable: Políticas para asegurar que la publicidad de Falabella sea legal, no discriminatoria, y respetuosa.
Financiamiento Responsable en Banco Falabella: Enfoque en créditos que consideren las capacidades de pago de los clientes, con educación financiera y foco en segmentos vulnerables.
Nutrición y Alimentación Saludable en Tottus: Estrategias para ofrecer alimentos saludables, educación en hábitos alimenticios y evitación del uso de químicos en productos.
/// Fin de información de la empresa

Antes de imprimir el resultado, revisa la información y verifica que cumples cada una de las instrucciones solicitadas y que los términos están correctamente escritos.

NO INCLUYAS UNA COPIA DE LA INFORMACIÓN DE LA EMPRESA EN TU RESPUESTA.

Muy importante, por favor entrega tus resultados en formato Markdown.

"""