# Generated by Django 4.2.3 on 2023-07-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_traitdb_personalitydb_agentdb_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdb',
            name='short_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
