# Generated by Django 4.2.3 on 2023-08-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentdb_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdb',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
