# Generated by Django 4.2.3 on 2023-09-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agentdb_show_in_explorer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('definition', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_title', models.CharField(blank=True, max_length=512, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='agents')),
            ],
        ),
    ]
