# Generated by Django 4.2.3 on 2023-09-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdb',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agents.agenttype'),
            preserve_default=False,
        ),
    ]
