# Generated by Django 4.2.3 on 2023-09-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_project_action'),
        ('chat', '0001_initial'),
        ('document', '0005_document_type'),
        ('actions', '0022_remove_action_previous_action'),
        ('agents', '0008_agentdb_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentDB',
            new_name='Agent',
        ),
    ]
