# Generated by Django 4.2.3 on 2023-09-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_rename_agentdb_agent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalityDB',
            new_name='Personality',
        ),
    ]
