# Generated by Django 4.2.3 on 2023-09-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_rename_traitdb_trait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='object',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
