# Generated by Django 4.2.3 on 2023-09-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_strategy'),
        ('agents', '0012_alter_agent_definition_alter_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, to='company.company'),
        ),
    ]
