# Generated by Django 4.2.3 on 2023-09-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_strategy'),
        ('agents', '0013_agent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='company',
            field=models.ManyToManyField(to='company.company'),
        ),
    ]
