# Generated by Django 4.1.11 on 2023-11-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_alter_agent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='traits',
            field=models.ManyToManyField(blank=True, to='agents.trait'),
        ),
    ]
