# This is a TOML document

name = "LinkedIn Post"
description = "Generate LinkedIn post from given document"
definition = ""
memory = "I generated a LinkedIn post"

[reply]
name = "format"
type = "format"

[prompt]
text = """
Generate a LinkedIn Post from the following document: 

{{document}}
"""