# Generated by Django 4.2.3 on 2023-07-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
