# Generated by Django 4.2.3 on 2023-07-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_message_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
