# Generated by Django 4.2.3 on 2023-07-28 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('projects', '0014_remove_documentelement_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='document_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documentelement'),
        ),
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.document'),
        ),
    ]
