# Generated by Django 4.2.3 on 2023-07-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_comment_document_element_project_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
