# Generated by Django 4.2.3 on 2023-07-30 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_actionformelement_guide'),
        ('projects', '0016_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.actiondb'),
        ),
    ]
