# Generated by Django 4.2.3 on 2023-07-30 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_instruction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='previous_instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.instruction'),
        ),
    ]
