# Generated by Django 4.2.3 on 2023-08-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_instruction_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectable', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.message')),
            ],
        ),
    ]
