# Generated by Django 4.2.3 on 2023-08-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_messageblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageblock',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
