# Generated by Django 4.2.3 on 2023-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_messageblock_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageblock',
            name='selectable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messageblock',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
