# Generated by Django 4.2.3 on 2023-08-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_messageblock_selectable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageblock',
            name='html',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
