# Generated by Django 4.2.3 on 2023-08-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_remove_message_instruction_delete_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageblock',
            name='message',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageBlock',
        ),
    ]
