# Generated by Django 4.2.3 on 2023-08-23 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0022_remove_action_previous_action'),
        ('projects', '0025_remove_messageblock_message_delete_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.action'),
        ),
    ]
