# Generated by Django 4.1.11 on 2023-10-03 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0027_project_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='action',
        ),
        migrations.RemoveField(
            model_name='project',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
