# Generated by Django 4.1.11 on 2023-10-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_project_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
