# Generated by Django 4.2.3 on 2023-07-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentelement',
            name='markdown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
