# Generated by Django 4.2.3 on 2023-08-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_documentelement_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentelement',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
