# Generated by Django 4.2.3 on 2023-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_documentelement_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('PRCH', 'Project Charter'), ('FBGD', 'Feedback Guideline')], default='PRCH', max_length=4),
        ),
    ]
