# Generated by Django 4.1.11 on 2023-09-14 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_alter_agent_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0005_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
        migrations.AddField(
            model_name='document',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
