# Generated by Django 4.1.11 on 2023-09-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_document_author_agent_document_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, choices=[('google_docs', 'Google Docs'), ('workwise', 'WorkWise')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='source_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='source_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
