# Generated by Django 4.1.11 on 2023-09-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='json',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text',
        ),
    ]
