# Generated by Django 4.1.11 on 2023-09-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_documentelement_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentelement',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
