# Generated by Django 4.1.11 on 2023-09-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_documentelement_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=256)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='document_sources')),
            ],
        ),
    ]
