# Generated by Django 4.1.11 on 2023-09-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_documentsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
