# Generated by Django 4.1.11 on 2023-10-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_alter_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_format',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.document'),
        ),
    ]
