# Generated by Django 4.1.11 on 2023-10-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0025_action_alpha_action_beta'),
        ('document', '0016_document_is_format_document_parent_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=256)),
                ('label', models.CharField(blank=True, max_length=256, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='document_formats')),
                ('actions', models.ManyToManyField(blank=True, to='actions.action')),
            ],
        ),
    ]
