# Generated by Django 4.1.11 on 2023-10-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_format',
        ),
        migrations.AddField(
            model_name='document',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.format'),
        ),
    ]
