# Generated by Django 4.1.11 on 2023-10-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_remove_document_is_format_document_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='format',
        ),
    ]
