# Generated by Django 4.1.11 on 2023-10-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_remove_document_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_format',
            field=models.BooleanField(default=False),
        ),
    ]
