# Generated by Django 4.1.11 on 2023-10-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_document_is_format'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Format',
        ),
    ]
