# Generated by Django 4.1.11 on 2023-10-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_delete_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_context',
            field=models.BooleanField(default=False),
        ),
    ]
