# Generated by Django 4.1.11 on 2023-10-16 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0023_document_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
