# Generated by Django 4.1.11 on 2023-10-17 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0024_document_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
