# Generated by Django 4.1.11 on 2023-10-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0025_alter_document_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sections',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
