# Generated by Django 4.1.11 on 2023-12-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0026_document_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
