# This is a TOML document

name = "Feedback Guidelines Alignment to Values"
description = ""
definition = ""
memory = "I aligned some Feedback Guidelines to the corporate values"

[reply]
name = "feedback_guidelines_values"
type = "document"

[prompt]
text = """Consider the following guideline to give criticism:

===
{{feedback}}
===

Now, please update the guidelines and recommendations considering the culture the company wants to develop. The new recommendation should communicate the company values and reinforce expected conducts. Here are the company values:

===
{{values}}
===

Please highlight the company values in the new feedback guidelines, using **bold font** in markdown format. Do not give me the old advise on feedback, just the new updated one.

This is very important: please provide your answer in Markdown format. 
"""