# Generated by Django 4.1.11 on 2023-11-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0025_action_alpha_action_beta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('index', models.IntegerField(default=0)),
                ('prompt', models.JSONField(default=dict)),
                ('action', models.ManyToManyField(blank=True, to='actions.action')),
            ],
        ),
    ]
