# Generated by Django 4.2.3 on 2023-07-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_actiondb_instruction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actiondb',
            old_name='instruction',
            new_name='definition',
        ),
    ]
