# Generated by Django 4.2.3 on 2023-07-29 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_rename_definition_actiondb_prompt_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionFormElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ActionFormElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('audio', models.BooleanField(default=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.actiondb')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.actionformelementtype')),
            ],
        ),
    ]
