# Generated by Django 4.2.3 on 2023-07-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_actionformelementtype_actionformelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionformelement',
            name='guide',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
