# Generated by Django 4.2.3 on 2023-07-30 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_actiondb_follow_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondb',
            name='previous_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.actiondb'),
        ),
    ]
