# Generated by Django 4.2.3 on 2023-07-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_actiondb_previous_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondb',
            name='action_label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
