# Generated by Django 4.2.3 on 2023-07-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_actiondb_action_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondb',
            name='identifier',
            field=models.CharField(default='Not set', max_length=256),
        ),
    ]
