# Generated by Django 4.2.3 on 2023-08-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0012_alter_actiondb_agent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActionFormElement',
            new_name='ActionElement',
        ),
    ]
