# Generated by Django 4.2.3 on 2023-08-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_rename_actiondb_action'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActionFormElementType',
            new_name='ActionElementType',
        ),
    ]
