# Generated by Django 4.2.3 on 2023-08-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0015_rename_actionformelementtype_actionelementtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionelementtype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='actionelementtype',
            name='name',
            field=models.CharField(choices=[('MSG', 'Message'), ('TXT', 'Text Input'), ('ACT', 'Action Call')], default='MSG', max_length=3),
        ),
    ]
