# Generated by Django 4.2.3 on 2023-08-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0016_alter_actionelementtype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionelement',
            name='guide',
            field=models.TextField(blank=True, null=True),
        ),
    ]
