# Generated by Django 4.2.3 on 2023-08-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0017_alter_actionelement_guide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionElement',
        ),
        migrations.DeleteModel(
            name='ActionElementType',
        ),
    ]
