# Generated by Django 4.2.3 on 2023-08-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0018_delete_actionelement_delete_actionelementtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='mimesis_class',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
