# Generated by Django 4.2.3 on 2023-08-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0008_alter_message_instruction'),
        ('actions', '0019_action_mimesis_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='first_instruction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_instruction_type', to='instruction.instructiontype'),
        ),
    ]
