# Generated by Django 4.2.3 on 2023-08-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0020_action_first_instruction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_label',
        ),
        migrations.RemoveField(
            model_name='action',
            name='follow_message',
        ),
        migrations.RemoveField(
            model_name='action',
            name='mimesis_class',
        ),
        migrations.RemoveField(
            model_name='action',
            name='prompt_instructions',
        ),
    ]
