# Generated by Django 4.2.3 on 2023-08-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0021_remove_action_action_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='previous_action',
        ),
    ]
