# Generated by Django 4.1.11 on 2023-09-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0023_rename_description_action_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
