# Generated by Django 4.1.11 on 2023-09-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0024_action_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='alpha',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='action',
            name='beta',
            field=models.BooleanField(default=True),
        ),
    ]
