# Generated by Django 4.1.11 on 2023-11-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_strategy_remove_company_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
