# Generated by Django 4.2.8 on 2024-01-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subdomain',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
