name = "Write Project Charter"
description = "Write a project charter"
definition = ""
memory = "I wrote a project charter"

[reply]
name = "project_charter"
type = "document"
revise = true

[prompt]
text = """Act as a senior project manager, with more than 20 years of experience in managing all kinds of projects.
        
Consider the following audio transcription describing a project:

=== project description

{{project_description}}

=== end of project description

From this project description, I want you to write a project charter.
Clarity is key: be clear and concise.
Avoid jargon and ensure that someone without domain knowledge can understand the project's basics.
The project charter should include the following elements:

1. Introduction

Purpose: Explain the purpose of the document.

Background: Contextualize why the project exists.

2. Project Sponsor and Stakeholders

Project Sponsor: Identify the sponsor who champions the project.

Stakeholders: List major stakeholders and their interests in the project. If no stakeholders where explicitly given, deduce and suggest possible stakeholders given the project context.

3. Project Objective

SMART Objectives: List of the project objectives. Each objective should follow the SMART (Specific, Measurable, Achievable, Relevant, Time-bound) framework.

4. Problem Statement or Business Case

Description: Clearly describe the problem or opportunity the project aims to address.

Metrics: Establish metrics to measure the problem and track improvements. If no metrics where given in the description, deduce and suggest possible metrics to measure the problem.

5. Project Scope

In-Scope: List what is included in the project.

Out-of-Scope: List what is explicitly not included in the project.

6. Deliverables

List: Provide a list of all deliverables.

Completeness Criteria: Describe the criteria for what constitutes a 'complete' deliverable.

{% if milestones %}
7. Milestones

Milestone List: Include significant project milestones and their expected dates.
{% endif %}

8. Constraints and Assumptions

Constraints: Limitations like time, resources, budget, or dependencies.

Assumptions: Things that are assumed to be in place but need verification.

9. Budget

Cost Estimates: Provide an initial estimate of costs.

Funding Source: Identify where the budget is coming from.

10. Governance and Approvals

Project Team: List roles and responsibilities.

Change Control: Describe the process for managing changes to the project.

Approvals: Mention who has the authority to approve different elements like budget changes, scope alteration, etc.

11. Risk Management

Risk Assessment: Identify potential risks and their severity.

Mitigation Plans: Describe risk management strategies.

12. Communication Plan

Communication Channels: Explain how and when communications will occur among stakeholders.

Documentation: State where all project documents will be stored and how they can be accessed.

13. Appendix

Glossary: Define any terminology or acronyms used.

=== end of project charter template

This is very important, when you don't find specific information in the project description given, use placeholders. For example, if you don't find the project title, write '<Project title>'.

Very important: please provide your answer using Markdown.
"""