# Generated by Django 4.1.11 on 2023-09-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_strategy'),
        ('agents', '0014_alter_agent_company'),
        ('user', '0006_profile_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agents',
            field=models.ManyToManyField(blank=True, to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='companies',
            field=models.ManyToManyField(blank=True, to='company.company'),
        ),
    ]
