# Generated by Django 4.1.11 on 2023-09-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alpha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='beta',
            field=models.BooleanField(default=False),
        ),
    ]
