# Generated by Django 4.1.11 on 2023-11-06 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_strategy_remove_company_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_patientinvitation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientInvitation',
            new_name='CompanyUserInvitation',
        ),
    ]
