# Generated by Django 4.1.11 on 2023-11-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_default'),
        ('user', '0011_rename_patientinvitation_companyuserinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='companies',
            field=models.ManyToManyField(blank=True, default=3, to='company.company'),
        ),
    ]
