# Generated by Django 4.1.11 on 2023-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='pitch',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='pitch_analysis_long',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='pitch_analysis_short',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='pitch_prompt',
            field=models.TextField(default=''),
        ),
    ]
