# Generated by Django 4.1.11 on 2023-11-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_default'),
        ('flow', '0002_alter_pitch_pitch_alter_pitch_pitch_analysis_long_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='flow_logos')),
                ('author_name', models.CharField(blank=True, max_length=256, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
