# Generated by Django 4.1.11 on 2023-11-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='title',
            field=models.CharField(default='Carozzi analiza tu pitch', max_length=256),
            preserve_default=False,
        ),
    ]
