# Generated by Django 4.1.11 on 2023-11-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_flow_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
