# Generated by Django 4.1.11 on 2023-11-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_alter_flow_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='author_name',
        ),
    ]
