# Generated by Django 4.1.11 on 2023-11-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0006_remove_flow_author_email_remove_flow_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='footer_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
