# Generated by Django 4.1.11 on 2023-11-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_flow_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='debug',
            field=models.BooleanField(default=False),
        ),
    ]
