# Generated by Django 4.1.11 on 2023-11-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0038_remove_instructionelementrevision_document_element_and_more'),
        ('flow', '0009_flow_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='instructions',
        ),
        migrations.AddField(
            model_name='flow',
            name='instruction_types',
            field=models.ManyToManyField(blank=True, to='instruction.instructiontype'),
        ),
    ]
