# Generated by Django 4.1.11 on 2023-11-29 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_project_default'),
        ('flow', '0010_remove_flow_instructions_flow_instruction_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='project',
            field=models.ForeignKey(default=203, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
    ]
