# Generated by Django 4.1.11 on 2023-11-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0025_action_alpha_action_beta'),
        ('flow', '0011_flow_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='action',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='actions.action'),
            preserve_default=False,
        ),
    ]
