# Generated by Django 4.1.11 on 2023-12-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0012_flow_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='style',
            field=models.CharField(choices=[('default', 'Default'), ('web', 'Web')], default='default', max_length=32),
        ),
    ]
