# Generated by Django 4.1.11 on 2023-12-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0013_flow_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='css',
            field=models.CharField(default='flow.css', max_length=64),
        ),
    ]
