# Generated by Django 4.1.11 on 2023-12-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0014_flow_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='register',
            field=models.BooleanField(default=False),
        ),
    ]
